services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
      - .env.local
      - .env.production
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/github/STACK:/STACK
    depends_on:
      - db
    networks:
      - services
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: furvino
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services

volumes:
  postgres_data: {}
networks:
  services:
    driver: bridge
  