services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.production
      - .env.local
      - .env.production.local
    environment:
      - NODE_ENV=production
      - STACK_ROOT=/STACK
    volumes:
      - type: bind
        source: ${STACK_HOST_ROOT:-/home/github/STACK}
        target: /STACK
        bind:
          create_host_path: false
    depends_on:
      - db
    networks:
      - services
  db:
    image: postgres:15-alpine
    env_file:
      - .env
      - .env.production
      - .env.local
      - .env.production.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services

volumes:
  postgres_data: {}
networks:
  services:
    driver: bridge
  