import type { Metadata } from "next";
import "./globals.css";
import BaseLayout from "../layout/BaseLayout";
import { Box, Container, Stack, Typography } from "@mui/material";
import { NovelsProvider, SearchProvider } from "@/novels/providers";
import { Header } from "@/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BaseLayout>
      <NovelsProvider>
        <SearchProvider>
          <Stack minHeight="100dvh">
            <Header />
            <Container sx={{ pb: 2 }}>{children}</Container>
            <Box flexGrow={1} />
            <Footer />
          </Stack>
        </SearchProvider>
      </NovelsProvider>
    </BaseLayout>
  );
}

function Footer() {
  return (
    <Box
      component="footer"
      sx={{ bgcolor: "background.paper", p: 2, mt: "auto" }}
    >
      <Typography variant="body2" color="text.secondary" align="center">
        &copy; {new Date().getFullYear()} FurViNo
      </Typography>
    </Box>
  );
}
