import type { Metadata } from "next";
import "./globals.css";
import { Box, Container, Stack, Typography } from "@mui/material";
import { Header, BaseLayout } from "@/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BaseLayout>
      <Stack minHeight="100dvh">
        <Header />
        <Container sx={{ pb: 2 }}>{children}</Container>
        <Box flexGrow={1} />
        <Footer />
      </Stack>
    </BaseLayout>
  );
}

function Footer() {
  return (
    <Box
      component="footer"
      sx={{ bgcolor: "background.paper", p: 2, mt: "auto" }}
    >
      <Typography variant="body2" color="text.secondary" align="center">
        &copy; {new Date().getFullYear()} FurViNo
      </Typography>
    </Box>
  );
}
