export * from './AndroidIcon';
export * from './DiscordIcon';
export * from './LinuxIcon';
export * from './MacIcon';
export * from './PatreonIcon';
export * from './TorrentIcon';
export * from './WindowsIcon';
export * from './TwitterXIcon';
export * from './ItchIcon';
