name: Dockerized Test on Self-Hosted Runner

on: [push]

jobs:
  test-in-container:
    # This job must run on a self-hosted runner with Docker installed
    runs-on: self-hosted

    # Specify the container for the job's steps
    container:
      image: node:20-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci