name: Main CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./build # Assuming 'npm run build' creates a 'build' directory

  deploy:
    name: Deploy to Server
    runs-on: self-hosted

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./build

      - name: Deploy to Nginx Directory
        run: |
          # Ensure the target directory exists
          sudo mkdir -p /var/www/my-react-app
          # Copy the built files to the web server root
          sudo cp -r./build/* /var/www/my-react-app/
          echo "Deployment complete."