# Based on [1, 35]
name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: trifumpy/furvino

jobs:
  test:
    name: Run Unit Tests
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: self-hosted
    needs: test # Run only after tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}