# Based on [38, 39]
name: Python Package CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint-and-test:
    name: Lint & Test on Python ${{ matrix.python-version }}
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint with flake8
      run: flake8. --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: self-hosted
    needs: lint-and-test # Run only after all test jobs succeed
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # Only run on tag push

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}